---
- name: Add sury repo key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"

- name: Add sury php
  apt_repository:
    repo: "deb https://packages.sury.org/php/ bookworm main"
    state: present
    filename: "sury-php"

- name: Install php8.4
  apt:
    name:
      - php8.4-fpm
      - php8.4-curl
      - php8.4-common
      - php8.4-mysql
      - php8.4-dev
      - php8.4-cli
      - php8.4-intl
      - php8.4-mbstring
      - php8.4-xml
      - php8.4-bcmath
      - php8.4-zip
      - php8.4-amqp
      - php8.4-decimal
      #- php8.4-igbinary
    state: present