services:
  nginx:
    container_name: 'nginx'
    build:
      context: .
      dockerfile: env/docker/nginx/Dockerfile
    cap_add:
      - SYS_PTRACE
    ports:
      - "80:80"
    volumes:
      - "./app/public:/app/public"
    networks:
      - treknparcel-network

  php:
    container_name: php
    build:
      context: .
      dockerfile: env/docker/php/Dockerfile
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - treknparcel-network
    environment:
      XDG_CONFIG_HOME: /tmp/.chromium
      XDG_CACHE_HOME: /tmp/.chromium
      PHP_IDE_CONFIG: 'serverName=host.docker.internal'
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "local.charts2pdf.com:host-gateway"

networks:
  treknparcel-network: