version: '3.8'

services:
  nginx:
    container_name: 'nginx'
    build:
      context: .
      dockerfile: env/docker/nginx/Dockerfile
    cap_add:
      - SYS_PTRACE
    ports:
      - "80:80"
    volumes:
      - "./app/public:/app/public"
    networks:
      - treknparcel-network

  php:
    container_name: php
    build:
      context: .
      dockerfile: env/docker/php/Dockerfile
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - treknparcel-network
    environment:
      PHP_IDE_CONFIG: 'serverName=host.docker.internal'

networks:
  treknparcel-network: