framework:
  html_sanitizer:
    sanitizers:
      main_sanitizer:
        allow_elements:
          p: []
          u: []
          s: []
          i: []
          b: []
          strong: []
          img: []
          span: []
        allow_attributes:
          style: '*'
          dir: '*'
          class: '*'
          src: '*'
        max_input_length: -1 # TODO set this to a reasonable value to protect against DDoS
        allowed_media_schemes: ['data']
        allowed_link_schemes: ['fake'] # empty array results in allowing all schemes