framework:
  html_sanitizer:
    sanitizers:
      main_sanitizer:
        allow_elements:
          p: []
          u: []
          s: []
          i: []
          b: []
          strong: []
          img: []
          span: []
        allow_attributes:
          style: '*'
          dir: '*'
          class: '*'
          src: '*'
        max_input_length: -1